package scrcpy

type ControlMessageType byte

const (
	CtrlInjectKeycode           ControlMessageType = 0
	CtrlInjectText              ControlMessageType = 1
	CtrlInjectTouchEvent        ControlMessageType = 2
	CtrlInjectScrollEvent       ControlMessageType = 3
	CtrlBackOrScreenOn          ControlMessageType = 4
	CtrlExpandNotificationPanel ControlMessageType = 5
	CtrlExpandSettingsPanel     ControlMessageType = 6
	CtrlCollapsePanels          ControlMessageType = 7
	CtrlGetClipboard            ControlMessageType = 8
	CtrlSetClipboard            ControlMessageType = 9
	CtrlSetScreenPowerMode      ControlMessageType = 10
	CtrlRotateDevice            ControlMessageType = 11
)

const (
	ActionDown byte = 0
	ActionUp   byte = 1
	ActionMove byte = 2
)

const (
	PowerModeOff = 0
	PowerModeOn  = 1
)

const (
	lenHandshake     = 65
	lenInjectKeycode = 14
	lenInjectTouch   = 28
	lenInjectScroll  = 21
)

const maxTextLength = 65535

const (
	videoFrame   = 65536
	controlFrame = 4096
)

const (
	AndroidKeyUnknown                   = 0
	AndroidKeySoftLeft                  = 1
	AndroidKeySoftRight                 = 2
	AndroidKeyHome                      = 3
	AndroidKeyBack                      = 4
	AndroidKeyCall                      = 5
	AndroidKeyEndcall                   = 6
	AndroidKey0                         = 7
	AndroidKey1                         = 8
	AndroidKey2                         = 9
	AndroidKey3                         = 10
	AndroidKey4                         = 11
	AndroidKey5                         = 12
	AndroidKey6                         = 13
	AndroidKey7                         = 14
	AndroidKey8                         = 15
	AndroidKey9                         = 16
	AndroidKeyStar                      = 17
	AndroidKeyPound                     = 18
	AndroidKeyDpadUp                    = 19
	AndroidKeyDpadDown                  = 20
	AndroidKeyDpadLeft                  = 21
	AndroidKeyDpadRight                 = 22
	AndroidKeyDpadCenter                = 23
	AndroidKeyVolumeUp                  = 24
	AndroidKeyVolumeDown                = 25
	AndroidKeyPower                     = 26
	AndroidKeyCamera                    = 27
	AndroidKeyClear                     = 28
	AndroidKeyA                         = 29
	AndroidKeyB                         = 30
	AndroidKeyC                         = 31
	AndroidKeyD                         = 32
	AndroidKeyE                         = 33
	AndroidKeyF                         = 34
	AndroidKeyG                         = 35
	AndroidKeyH                         = 36
	AndroidKeyI                         = 37
	AndroidKeyJ                         = 38
	AndroidKeyK                         = 39
	AndroidKeyL                         = 40
	AndroidKeyM                         = 41
	AndroidKeyN                         = 42
	AndroidKeyO                         = 43
	AndroidKeyP                         = 44
	AndroidKeyQ                         = 45
	AndroidKeyR                         = 46
	AndroidKeyS                         = 47
	AndroidKeyT                         = 48
	AndroidKeyU                         = 49
	AndroidKeyV                         = 50
	AndroidKeyW                         = 51
	AndroidKeyX                         = 52
	AndroidKeyY                         = 53
	AndroidKeyZ                         = 54
	AndroidKeyComma                     = 55
	AndroidKeyPeriod                    = 56
	AndroidKeyAltLeft                   = 57
	AndroidKeyAltRight                  = 58
	AndroidKeyShiftLeft                 = 59
	AndroidKeyShiftRight                = 60
	AndroidKeyTab                       = 61
	AndroidKeySpace                     = 62
	AndroidKeySym                       = 63
	AndroidKeyExplorer                  = 64
	AndroidKeyEnvelope                  = 65
	AndroidKeyEnter                     = 66
	AndroidKeyDel                       = 67
	AndroidKeyGrave                     = 68
	AndroidKeyMinus                     = 69
	AndroidKeyEquals                    = 70
	AndroidKeyLeftBracket               = 71
	AndroidKeyRightBracket              = 72
	AndroidKeyBackslash                 = 73
	AndroidKeySemicolon                 = 74
	AndroidKeyApostrophe                = 75
	AndroidKeySlash                     = 76
	AndroidKeyAt                        = 77
	AndroidKeyNum                       = 78
	AndroidKeyHeadsethook               = 79
	AndroidKeyFocus                     = 80
	AndroidKeyPlus                      = 81
	AndroidKeyMenu                      = 82
	AndroidKeyNotification              = 83
	AndroidKeySearch                    = 84
	AndroidKeyMediaPlayPause            = 85
	AndroidKeyMediaStop                 = 86
	AndroidKeyMediaNext                 = 87
	AndroidKeyMediaPrevious             = 88
	AndroidKeyMediaRewind               = 89
	AndroidKeyMediaFastForward          = 90
	AndroidKeyMute                      = 91
	AndroidKeyPageUp                    = 92
	AndroidKeyPageDown                  = 93
	AndroidKeyPictsymbols               = 94
	AndroidKeySwitchCharset             = 95
	AndroidKeyButtonA                   = 96
	AndroidKeyButtonB                   = 97
	AndroidKeyButtonC                   = 98
	AndroidKeyButtonX                   = 99
	AndroidKeyButtonY                   = 100
	AndroidKeyButtonZ                   = 101
	AndroidKeyButtonL1                  = 102
	AndroidKeyButtonR1                  = 103
	AndroidKeyButtonL2                  = 104
	AndroidKeyButtonR2                  = 105
	AndroidKeyButtonThumbl              = 106
	AndroidKeyButtonThumbr              = 107
	AndroidKeyButtonStart               = 108
	AndroidKeyButtonSelect              = 109
	AndroidKeyButtonMode                = 110
	AndroidKeyEscape                    = 111
	AndroidKeyForwardDel                = 112
	AndroidKeyCtrlLeft                  = 113
	AndroidKeyCtrlRight                 = 114
	AndroidKeyCapsLock                  = 115
	AndroidKeyScrollLock                = 116
	AndroidKeyMetaLeft                  = 117
	AndroidKeyMetaRight                 = 118
	AndroidKeyFunction                  = 119
	AndroidKeySysrq                     = 120
	AndroidKeyBreak                     = 121
	AndroidKeyMoveHome                  = 122
	AndroidKeyMoveEnd                   = 123
	AndroidKeyForward                   = 125
	AndroidKeyMediaPlay                 = 126
	AndroidKeyMediaPause                = 127
	AndroidKeyMediaClose                = 128
	AndroidKeyMediaEject                = 129
	AndroidKeyMediaRecord               = 130
	AndroidKeyF1                        = 131
	AndroidKeyF2                        = 132
	AndroidKeyF3                        = 133
	AndroidKeyF4                        = 134
	AndroidKeyF5                        = 135
	AndroidKeyF6                        = 136
	AndroidKeyF7                        = 137
	AndroidKeyF8                        = 138
	AndroidKeyF9                        = 139
	AndroidKeyF10                       = 140
	AndroidKeyF11                       = 141
	AndroidKeyF12                       = 142
	AndroidKeyNumLock                   = 143
	AndroidKeyNumpad0                   = 144
	AndroidKeyNumpad1                   = 145
	AndroidKeyNumpad2                   = 146
	AndroidKeyNumpad3                   = 147
	AndroidKeyNumpad4                   = 148
	AndroidKeyNumpad5                   = 149
	AndroidKeyNumpad6                   = 150
	AndroidKeyNumpad7                   = 151
	AndroidKeyNumpad8                   = 152
	AndroidKeyNumpad9                   = 153
	AndroidKeyNumpadDivide              = 154
	AndroidKeyNumpadMultiply            = 155
	AndroidKeyNumpadSubtract            = 156
	AndroidKeyNumpadAdd                 = 157
	AndroidKeyNumpadDot                 = 158
	AndroidKeyNumpadComma               = 159
	AndroidKeyNumpadEnter               = 160
	AndroidKeyNumpadEquals              = 161
	AndroidKeyNumpadLeftParen           = 162
	AndroidKeyNumpadRightParen          = 163
	AndroidKeyVolumeMute                = 164
	AndroidKeyInfo                      = 165
	AndroidKeyChannelUp                 = 166
	AndroidKeyChannelDown               = 167
	AndroidKeyZoomIn                    = 168
	AndroidKeyZoomOut                   = 169
	AndroidKeyTv                        = 170
	AndroidKeyWindow                    = 171
	AndroidKeyGuide                     = 172
	AndroidKeyDvr                       = 173
	AndroidKeyBookmark                  = 174
	AndroidKeyCaptions                  = 175
	AndroidKeySettings                  = 176
	AndroidKeyTvPower                   = 177
	AndroidKeyTvInput                   = 178
	AndroidKeyStbPower                  = 179
	AndroidKeyStbInput                  = 180
	AndroidKeyAppSwitch                 = 187
	AndroidKeyButton1                   = 188
	AndroidKeyButton2                   = 189
	AndroidKeyButton3                   = 190
	AndroidKeyButton4                   = 191
	AndroidKeyButton5                   = 192
	AndroidKeyButton6                   = 193
	AndroidKeyButton7                   = 194
	AndroidKeyButton8                   = 195
	AndroidKeyButton9                   = 196
	AndroidKeyButton10                  = 197
	AndroidKeyButton11                  = 198
	AndroidKeyButton12                  = 199
	AndroidKeyButton13                  = 200
	AndroidKeyButton14                  = 201
	AndroidKeyButton15                  = 202
	AndroidKeyButton16                  = 203
	AndroidKeyLanguageSwitch            = 204
	AndroidKeyMannerMode                = 205
	AndroidKey3dMode                    = 206
	AndroidKeyContacts                  = 207
	AndroidKeyCalendar                  = 208
	AndroidKeyMusic                     = 209
	AndroidKeyCalculator                = 210
	AndroidKeyZenkakuHankaku            = 211
	AndroidKeyEisu                      = 212
	AndroidKeyMuhenkan                  = 213
	AndroidKeyHenkan                    = 214
	AndroidKeyKatakanaHiragana          = 215
	AndroidKeyYen                       = 216
	AndroidKeyRo                        = 217
	AndroidKeyKana                      = 218
	AndroidKeyAssist                    = 219
	AndroidKeyBrightnessDown            = 220
	AndroidKeyBrightnessUp              = 221
	AndroidKeyMediaAudioTrack           = 222
	AndroidKeySleep                     = 223
	AndroidKeyWakeup                    = 224
	AndroidKeyPairing                   = 225
	AndroidKeyMediaTopMenu              = 226
	AndroidKey11                        = 227
	AndroidKey12                        = 228
	AndroidKeyLastChannel               = 229
	AndroidKeyTvDataService             = 230
	AndroidKeyVoiceAssist               = 231
	AndroidKeyTvTeletext                = 233
	AndroidKeyTvNumberEntry             = 234
	AndroidKeyTvTerrestrialAnalog       = 235
	AndroidKeyTvTerrestrialDigital      = 236
	AndroidKeyTvSatellite               = 237
	AndroidKeyTvSatelliteBs             = 238
	AndroidKeyTvSatelliteCs             = 239
	AndroidKeyTvSatelliteService        = 240
	AndroidKeyTvNetwork                 = 241
	AndroidKeyTvAntennaCable            = 242
	AndroidKeyTvInputHdmi1              = 243
	AndroidKeyTvInputHdmi2              = 244
	AndroidKeyTvInputHdmi3              = 245
	AndroidKeyTvInputHdmi4              = 246
	AndroidKeyTvInputComposite1         = 247
	AndroidKeyTvInputComposite2         = 248
	AndroidKeyTvInputComponent1         = 249
	AndroidKeyTvInputComponent2         = 250
	AndroidKeyTvInputVga1               = 251
	AndroidKeyTvAudioDescriptionMixUp   = 253
	AndroidKeyTvAudioDescriptionMixDown = 254
	AndroidKeyTvZoomMode                = 255
	AndroidKeyTvContentsMenu            = 256
	AndroidKeyTvMediaContextMenu        = 257
	AndroidKeyTvTimerProgramming        = 258
	AndroidKeyHelp                      = 259
	AndroidKeyNavigatePrevious          = 260
	AndroidKeyNavigateNext              = 261
	AndroidKeyNavigateIn                = 262
	AndroidKeyNavigateOut               = 263
	AndroidKeyStem1                     = 265
	AndroidKeyStem2                     = 266
	AndroidKeyStem3                     = 267
	AndroidKeyDpadUpLeft                = 268
	AndroidKeyDpadDownLeft              = 269
	AndroidKeyDpadUpRight               = 270
	AndroidKeyDpadDownRight             = 271
	AndroidKeyMediaSkipForward          = 272
	AndroidKeyMediaSkipBackward         = 273
	AndroidKeyMediaStepForward          = 274
	AndroidKeyMediaStepBackward         = 275
	AndroidKeySoftSleep                 = 276
	AndroidKeyCut                       = 277
	AndroidKeyCopy                      = 278
	AndroidKeyPaste                     = 279
	AndroidKeySystemNavigationUp        = 280
	AndroidKeySystemNavigationDown      = 281
	AndroidKeySystemNavigationLeft      = 282
	AndroidKeySystemNavigationRight     = 283
	AndroidKeyAllApps                   = 284
	AndroidKeyRefresh                   = 285
	AndroidKeyThumbsUp                  = 286
	AndroidKeyThumbsDown                = 287
	AndroidKeyProfileSwitch             = 288
	AndroidKeyVideoApp1                 = 289
	AndroidKeyVideoApp2                 = 290
	AndroidKeyVideoApp3                 = 291
	AndroidKeyVideoApp4                 = 292
	AndroidKeyVideoApp5                 = 293
	AndroidKeyVideoApp6                 = 294
	AndroidKeyVideoApp7                 = 295
	AndroidKeyVideoApp8                 = 296
	AndroidKeyFeaturedApp1              = 297
	AndroidKeyFeaturedApp2              = 298
	AndroidKeyFeaturedApp3              = 299
	AndroidKeyFeaturedApp4              = 300
	AndroidKeyDemoApp1                  = 301
	AndroidKeyDemoApp2                  = 302
	AndroidKeyDemoApp3                  = 303
	AndroidKeyDemoApp4                  = 304
	AndroidKeyKeyboardBacklightDown     = 305
	AndroidKeyKeyboardBacklightUp       = 306
	AndroidKeyStylusButtonPrimary       = 308
	AndroidKeyStylusButtonSecondary     = 309
	AndroidKeyStylusButtonTertiary      = 310
	AndroidKeyStylusButtonTail          = 311
	AndroidKeyRecentApps                = 312
	AndroidKeyMacro1                    = 313
	AndroidKeyMacro2                    = 314
	AndroidKeyMacro3                    = 315
	AndroidKeyMacro4                    = 316
	AndroidKeyEmojiPicker               = 317
	AndroidKeyScreenshot                = 318
	AndroidKeyDictate                   = 319
	AndroidKeyNew                       = 320
	AndroidKeyClose                     = 321
	AndroidKeyDoNotDisturb              = 322
	AndroidKeyPrint                     = 323
	AndroidKeyLock                      = 324
	AndroidKeyFullscreen                = 325
	AndroidKeyF13                       = 326
	AndroidKeyF14                       = 327
	AndroidKeyF15                       = 328
	AndroidKeyF16                       = 329
	AndroidKeyF17                       = 330
	AndroidKeyF18                       = 331
	AndroidKeyF19                       = 332
	AndroidKeyF20                       = 333
	AndroidKeyF21                       = 334
	AndroidKeyF22                       = 335
	AndroidKeyF23                       = 336
	AndroidKeyF24                       = 337
)
